SELECT * FROM USER;

SELECT * FROM BOOK;

SELECT * FROM READING_LOG WHERE USER_ID = 'user01' AND STATUS = 'FINISHED';

SELECT * FROM COMMENT WHERE USER_ID = 'user01' AND LOG_IDX = 39;

SELECT * FROM READING_LOG;

SELECT * FROM QUOTE;

SELECT * FROM COMMENT;

SELECT * FROM TAG;

SELECT * FROM READING_LOG_TAG;

SELECT * FROM READING_LOG_LIKE;

SELECT * FROM FOLLOW;

SELECT * FROM MESSAGE;

SHOW CREATE TABLE USER;

SHOW CREATE TABLE READING_LOG;

ALTER TABLE READING_LOG
DROP COLUMN LIKE_COUNT;

DELETE FROM READING_LOG
WHERE LOG_IDX = 53 OR LOG_IDX = 54 OR LOG_IDX = 55;

DELETE FROM USER
WHERE USER_ID = 'user05' OR USER_ID = 'user04';

ALTER TABLE READING_LOG DROP CHECK CK_RATING;

-- CK_RATING 제약조건 추후 수정 필요 
ALTER TABLE READING_LOG
ADD CONSTRAINT CK_RATING CHECK (
    RATING IS NULL OR (RATING >= 0 AND RATING <= 5.0)
);

SHOW COLUMNS FROM READING_LOG LIKE 'RATING';

SHOW CREATE TABLE USER;

-- USER 테이블에 NAME 컬럼 추가
ALTER TABLE USER
ADD COLUMN NAME VARCHAR(50) NOT NULL AFTER USER_ID;

-- 1. QUOTE 테이블 비우기
TRUNCATE TABLE QUOTE;

-- 2. READING_LOG_TAG 테이블 비우기
TRUNCATE TABLE READING_LOG_TAG;

-- 3. READING_LOG 테이블 비우기
TRUNCATE TABLE READING_LOG;

-- 4. BOOK 테이블 비우기
TRUNCATE TABLE BOOK;

TRUNCATE TABLE TAG;

TRUNCATE TABLE COMMENT;

TRUNCATE TABLE FOLLOW;
